name: Build and Commit Resume

on:
  push:
    branches: [master]
    paths:
      - resume.tex

jobs:
  compile:
    name: Compile resume PDF
    runs-on: ubuntu-latest

    steps:
      - name: Check out PDF repo
        uses: actions/checkout@v4
        with:
          repository: sahrohit/sahrohit

      - name: Run the build process with Docker
        uses: addnab/docker-run-action@v3
        with:
          image: thomasweise/docker-texlive-full:latest
          options: -v ${{ github.workspace }}:/data
          run: |
            cd data
            pdflatex resume.tex

      - name: Upload PDF artifact
        uses: actions/upload-artifact@v3
        with:
          name: resume-pdf
          path: resume.pdf

      - name: Commit and push changes
        uses: stefanzweifel/git-auto-commit-action@v5
        with:
          commit_message: Updated Resume PDF

  commit:
    name: Commit resume PDF
    needs: compile
    runs-on: ubuntu-latest

    steps:
      - name: Check out portfolio repo
        uses: actions/checkout@v4
        with:
          repository: sahrohit/portfolio
          token: ${{ secrets.ACCESS_TOKEN }}

      - name: Download PDF artifact
        uses: actions/download-artifact@v3
        with:
          name: resume-pdf

      - name: Move PDF to public directory
        run: |
          mv resume.pdf public/"Rohit's-Resume.pdf"

      - name: Commit and push changes
        uses: stefanzweifel/git-auto-commit-action@v5
        with:
          commit_message: Updated Resume PDF
